# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    # below can be used for full update of repo
    # directories:
    #   - "**/*"
    directory:  "/deployments/gpu-operator"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"
      time: "15:05"
      timezone: "Asia/Kolkata"
    registries:
      - nvcr-repo

  - package-ecosystem: "docker"
    directory:  "/bundle/manifests"
    open-pull-requests-limit: 15
    schedule:
      interval: "daily"
      time: "17:45"
      timezone: "Asia/Kolkata"
    registries:
      - nvcr-repo

 
registries:
  nvcr-repo:
   type: "docker-registry"
   url: "https://nvcr.io"
   username: ${{secrets.REGISTRY_USER}}
   password: ${{secrets.REGISTRY_PASSWORD}}
