name: Renovate

on:
  workflow_dispatch:
  schedule:
    # - cron: "*/15 * * * *"
    - cron: "0 0 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.1
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.GITHUB_TOKEN }}
          allowed_repos:
            - "**"
        env:
          RENOVATE_TOKEN: ${{ secrets.REGISTRY_PASSWORD }}
  