name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.1
        with:
          configurationFile: .github/renovate.js
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  